testexamples: script to test all examples or to rebuild all .out files
flask_restful.mochi.out and timer.mochi.out has been rebuilt to avoid false
positive (testexamples expects a different current dir than previously when
these 2 .out files were built).

As of now, the following example failures are observed (with Docker image
tlvu/mochi:0.2.4.2-20150508).  The simple reason is because the examples do not
produce identical output between different runs.

Not sure how to fix these examples.

$ ./testexamples
18c18
< 0.0025186538696289062 5
---
> 0.002317190170288086 5
24c24
< <function _gs126.<locals>.fafa at 0x7fbd67d047b8>
---
> <function _gs126.<locals>.fafa at 0x7f90df7e47b8>
ERROR: etc.mochi changed
4c4
< time: 0.07205533981323242
---
> time: 0.0695199966430664
ERROR: fact.mochi changed
4c4
< time: 0.15062212944030762
---
> time: 0.1504371166229248
ERROR: fact_pattern.mochi changed
2c2
< pmap({'a': 1, 'b': 2})
---
> pmap({'b': 2, 'a': 1})
5c5
< pmap({'a': 1, 'b': 2})
---
> pmap({'b': 2, 'a': 1})
ERROR: keyword_arguments.mochi changed
1c1
< 23.061758756637573 1
---
> 22.92900848388672 1
ERROR: tak.mochi changed
3a4
> 明後日 雨のち晴
7a9
> 明後日 雨のち晴
11a14
> 明後日 晴れ
ERROR: urlopen.mochi changed